"""initial schema

Revision ID: 63588f9af7ab
Revises:
Create Date: 2026-07-30 12:21:14.580326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63588f9af7ab"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_courses_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "course_memberships",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'teacher', 'student')", name=op.f("ck_course_memberships_valid_role")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_memberships_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("course_id", "user_id", name=op.f("pk_course_memberships")),
    )
    with op.batch_alter_table("course_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_course_memberships_user_course", ["user_id", "course_id"], unique=False
        )

    op.create_table(
        "decks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_decks_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decks")),
    )
    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decks_course_id"), ["course_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("deck_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_conversations_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
            name=op.f("fk_conversations_deck_id_decks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "deck_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deck_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_file_path", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("chunking_version", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding_version", sa.String(length=64), nullable=False),
        sa.Column("retrieval_schema_version", sa.String(length=64), nullable=False),
        sa.Column("slide_count", sa.Integer(), nullable=False),
        sa.Column("textless_slide_count", sa.Integer(), nullable=False),
        sa.Column("expected_chunk_count", sa.Integer(), nullable=False),
        sa.Column("indexed_chunk_count", sa.Integer(), nullable=False),
        sa.Column("index_manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("index_status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "index_status IN ('pending','indexing','in_sync','failed','drifted')",
            name=op.f("ck_deck_versions_valid_index_status"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded','parsing','chunking','indexing','ready',"
            "'failed','unsupported_textless_pdf')",
            name=op.f("ck_deck_versions_valid_status"),
        ),
        sa.CheckConstraint(
            "embedding_dimensions = 1536", name=op.f("ck_deck_versions_embedding_dimensions_1536")
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
            name=op.f("fk_deck_versions_deck_id_decks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deck_versions")),
        sa.UniqueConstraint("deck_id", "version_number", name=op.f("uq_deck_versions_deck_id")),
    )
    with op.batch_alter_table("deck_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deck_versions_deck_id"), ["deck_id"], unique=False)

    op.create_foreign_key(
        "fk_decks_active_version",
        "decks",
        "deck_versions",
        ["active_version_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deck_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','failed')",
            name=op.f("ck_ingestion_jobs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["deck_version_id"],
            ["deck_versions.id"],
            name=op.f("fk_ingestion_jobs_deck_version_id_deck_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint("deck_version_id", name=op.f("uq_ingestion_jobs_deck_version_id")),
    )
    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingestion_jobs_available_at"), ["available_at"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("current_slide_id", sa.Uuid(), nullable=True),
        sa.Column("selected_text", sa.Text(), nullable=True),
        sa.Column("retrieved_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("citations_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant','system')", name=op.f("ck_messages_valid_role")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "retrieval_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("deck_id", sa.Uuid(), nullable=False),
        sa.Column("deck_version_id", sa.Uuid(), nullable=False),
        sa.Column("current_slide_id", sa.Uuid(), nullable=False),
        sa.Column("original_query", sa.Text(), nullable=False),
        sa.Column("rewritten_query", sa.Text(), nullable=False),
        sa.Column("selected_text_match", sa.JSON(), nullable=True),
        sa.Column("filters_json", sa.JSON(), nullable=False),
        sa.Column("candidates_json", sa.JSON(), nullable=False),
        sa.Column("final_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("timings_json", sa.JSON(), nullable=False),
        sa.Column("model_config_json", sa.JSON(), nullable=False),
        sa.Column("inconsistency_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_retrieval_runs_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_runs")),
    )
    op.create_table(
        "slides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deck_version_id", sa.Uuid(), nullable=False),
        sa.Column("slide_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("section", sa.String(length=500), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("previous_slide_id", sa.Uuid(), nullable=True),
        sa.Column("next_slide_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deck_version_id"],
            ["deck_versions.id"],
            name=op.f("fk_slides_deck_version_id_deck_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slides")),
        sa.UniqueConstraint(
            "deck_version_id", "slide_number", name=op.f("uq_slides_deck_version_id")
        ),
    )
    with op.batch_alter_table("slides", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_slides_deck_version_id"), ["deck_version_id"], unique=False
        )
        batch_op.create_index(
            "ix_slides_version_number", ["deck_version_id", "slide_number"], unique=False
        )

    op.create_table(
        "vector_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deck_version_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('INDEX_DECK_VERSION','DELETE_DECK_VERSION','REBUILD_COLLECTION')",
            name=op.f("ck_vector_outbox_valid_event_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','failed')",
            name=op.f("ck_vector_outbox_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["deck_version_id"],
            ["deck_versions.id"],
            name=op.f("fk_vector_outbox_deck_version_id_deck_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vector_outbox")),
    )
    with op.batch_alter_table("vector_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vector_outbox_available_at"), ["available_at"], unique=False
        )
        batch_op.create_index("ix_vector_outbox_claim", ["status", "available_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_vector_outbox_deck_version_id"), ["deck_version_id"], unique=False
        )

    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deck_version_id", sa.Uuid(), nullable=False),
        sa.Column("slide_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding_text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deck_version_id"],
            ["deck_versions.id"],
            name=op.f("fk_chunks_deck_version_id_deck_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["slide_id"], ["slides.id"], name=op.f("fk_chunks_slide_id_slides"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "deck_version_id", "slide_id", "ordinal", name=op.f("uq_chunks_deck_version_id")
        ),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chunks_deck_version_id"), ["deck_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chunks_slide_id"), ["slide_id"], unique=False)
        batch_op.create_index(
            "ix_chunks_version_slide", ["deck_version_id", "slide_id"], unique=False
        )

    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_feedback_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_message_id"), ["message_id"], unique=False)

    op.create_table(
        "slide_blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slide_id", sa.Uuid(), nullable=False),
        sa.Column("block_type", sa.String(length=40), nullable=False),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("bullet_level", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["slide_id"],
            ["slides.id"],
            name=op.f("fk_slide_blocks_slide_id_slides"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slide_blocks")),
        sa.UniqueConstraint("slide_id", "reading_order", name=op.f("uq_slide_blocks_slide_id")),
    )
    with op.batch_alter_table("slide_blocks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_slide_blocks_slide_id"), ["slide_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slide_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_slide_blocks_slide_id"))

    op.drop_table("slide_blocks")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_message_id"))

    op.drop_table("feedback")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_chunks_version_slide")
        batch_op.drop_index(batch_op.f("ix_chunks_slide_id"))
        batch_op.drop_index(batch_op.f("ix_chunks_deck_version_id"))

    op.drop_table("chunks")
    with op.batch_alter_table("vector_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vector_outbox_deck_version_id"))
        batch_op.drop_index("ix_vector_outbox_claim")
        batch_op.drop_index(batch_op.f("ix_vector_outbox_available_at"))

    op.drop_table("vector_outbox")
    with op.batch_alter_table("slides", schema=None) as batch_op:
        batch_op.drop_index("ix_slides_version_number")
        batch_op.drop_index(batch_op.f("ix_slides_deck_version_id"))

    op.drop_table("slides")
    op.drop_table("retrieval_runs")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))

    op.drop_table("messages")
    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_jobs_available_at"))

    op.drop_table("ingestion_jobs")
    with op.batch_alter_table("deck_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deck_versions_deck_id"))

    op.drop_constraint("fk_decks_active_version", "decks", type_="foreignkey")
    op.drop_table("deck_versions")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decks_course_id"))

    op.drop_table("decks")
    with op.batch_alter_table("course_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_course_memberships_user_course")

    op.drop_table("course_memberships")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courses_owner_id"))

    op.drop_table("courses")
    # ### end Alembic commands ###
